using Microsoft.Extensions.FileProviders;

namespace VueJSMVCDotNet.Options
{
    /// <summary>
    /// Used to supply the additional configurations for the different middleware components
    /// </summary>
    public class VueMiddlewareOptions
    {
        /// <summary>
        /// Optional: An instance of a log writer class to write the logging information to
        /// </summary>
        public ILogger? LogWriter { get; init; } = null;
        /// <summary>
        /// Optional: The import path for the VueJs library: default="https://unpkg.com/vue@3/dist/vue.runtime.esm-browser.prod.js"
        /// </summary>
        public string VueImportPath { get; init; } = "https://unpkg.com/vue@3/dist/vue.runtime.esm-browser.prod.js";
        /// <summary>
        /// Optional: The import path for the Vue-Loader library: default="https://unpkg.com/vue3-sfc-loader@0.9.5/dist/vue3-sfc-loader.esm.js"
        /// </summary>
        public string VueLoaderImportPath { get; init; } = "https://unpkg.com/vue3-sfc-loader@0.9.5/dist/vue3-sfc-loader.esm.js";
        /// <summary>
        /// Optional: This will remap the core JS url that is imported by all classes to a different path
        /// </summary>
        public string CoreJSURL { get; init; } = "/VueJSMVCDotNet_core.min.js";
        /// <summary>
        /// Optional:  This will change the import call from the core js url to the module name
        /// </summary>
        public string? CoreJSImport { get; init; } = null;
        /// <summary>
        /// An instance of a file provider, required if using VueFiles or Messages
        /// </summary>
        public IFileProvider? FileProvider { get; init; } = null;
        /// <summary>
        /// Optional: must be provided in order to use the IModel and autogenerated Models/Rest interfaces
        /// </summary>
        public VueModelsOptions? VueModelsOptions { get; init; } = null;
        /// <summary>
        /// Optional: to be provided if the message translator component is to be used
        /// </summary>
        public MessageHandlerOptions? MessageOptions { get; init; } = null;
        /// <summary>
        /// Optional: Settings to be used file the Vue File handler
        /// </summary>
        public VueFilesHandlerOptions? VueFilesOptions { get; init; } = null;
        /// <summary>
        /// Optional: If set to true this will compress all outputted javascript, whether or not the requesting url ends with min.js or .js
        /// </summary>
        public bool CompressAllJS { get; init; } = false;

        private VueMiddleware? middleWare = null;

        internal void SetVueMiddleware(VueMiddleware value)
            => middleWare = value;
        /// <summary>
        /// called when an assemblyloadcontext needs to be unloaded, this will remove all references to 
        /// that load context to allow for an unload
        /// </summary>
        /// <param name="context">The assembly context being unloaded</param>
        public void UnloadAssemblyContext(AssemblyLoadContext context)
            => UnloadAssemblyContext(context.Name);

        /// <summary>
        /// called when an assembly context needs to be unloaded without providing the context but its name
        /// instead
        /// </summary>
        /// <param name="contextName">The name of the assembly load context to unload</param>
        public void UnloadAssemblyContext(string? contextName)
            => middleWare?.UnloadAssemblyContext(contextName);

        /// <summary>
        /// Called when a new Assembly Load Context has been added
        /// </summary>
        /// <param name="contextName">The name of the context that was added</param>
        public void AsssemblyLoadContextAdded(string? contextName)
            => middleWare?.AsssemblyLoadContextAdded(contextName);

        /// <summary>
        /// Called when a new Assembly Load Context has been added
        /// </summary>
        /// <param name="alc">The assembly load context that was added</param>
        /// <exception cref="ModelValidationException">Houses a set of exceptions if any newly loaded models fail validation</exception>
        public void AsssemblyLoadContextAdded(AssemblyLoadContext alc)
            => AsssemblyLoadContextAdded(alc.Name);

        ///<summary>
        ///called when a new assembly has been loaded in the case of dynamic loading, in order 
        ///to rescan for all new model types and add them accordingly.
        ///</summary>
        public void AssemblyAdded()
            => middleWare?.AssemblyAdded();
    }
}
