name: .NET-Test-6x

on:
  push:
    branches: [ 'version_3' ]
  pull_request:
    branches: [ 'version_3' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          6.0.x
    - name: Build-6.0
      run: dotnet build --framework net6.0 AutomatedTesting
    - name: Test-6.0
      run: dotnet test --framework net6.0 --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover AutomatedTesting
    - name: Codecov coverage upload
      uses: codecov/codecov-action@v3.1.1
